// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CloseAllTabs
{
    static class Vsix
    {
        public const string Id = "55640f47-34bc-436b-8820-e7f64fbb31fc";
        public const string Name = "Clean Solution";
        public const string Description = @"Cleans up the solution for the next time you open it. Closes open documents and collapses folders automatically when a solution is being closed. ";
        public const string Language = "en-US";
        public const string Version = "1.4.1";
        public const string Author = "Mads Kristensen";
        public const string Tags = "tabs, cleanup, collapse";
    }
}
